(define-module (synnax services datomic)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (guix store)
  #:use-module (guix records)
  #:use-module (gnu)
  #:use-module (gnu services)
  #:use-module (gnu services configuration)
  #:use-module (gnu services shepherd)
  #:use-module (gnu system shadow)
  #:use-module (gnu packages)
  #:use-module (gnu packages admin)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages java)
  #:use-module (ice-9 match)
  #:use-module (synnax packages datomic)
  #:export (datomic-transactor-service-type
            datomic-transactor-configuration))

(define (serialize-string field-name value)
  #~(string-append
     #$(symbol->string field-name) "=" #$value "\n"))

(define (serialize-integer field-name value)
  #~(string-append
     #$(symbol->string field-name) "=" #$(number->string value) "\n"))

(define (serialize-transactor-configuration config)
  (mixed-text-file
   "transactor.properties"
   #~(string-append
      "## Generated by Guix. DO NOT EDIT! ##\n"
      #$(serialize-configuration
         config
         datomic-transactor-configuration-fields))))

(define-configuration datomic-transactor-configuration
  (package
    (package datomic)
    "Datomic package to use.")
  (protocol
   (string "dev")
   "Transactor protocol type. Defaults to \"dev\" for development.
NOTE: The development database @emph{is} persistent! It is written out to the
datomic user's home directory.")
  (host
    (string "localhost")
    "IP address or FQDN for this transactor to listen on.")
  (port
   (integer 4334)
   "Port that the transactor listens on.")
  (pid-file
   (string "/var/run/datomic/datomic-transactor.pid")
   "Location of Datomic PID file.")
  (data-dir
   (string "/var/run/datomic")
   "Temporary working directory for Datomic transactor data.")
  (log-dir
   (string "/var/log/datomic")
   "Datomic transactor log file.")
  ;; set carefully. you can get
  ;; 2025-10-31 12:19:48 Terminating process - Error starting transactor
  ;; 2025-10-31 12:19:48 java.lang.IllegalArgumentException: :db.error/not-enough-memory (datomic.objectCacheMax + datomic.memoryIndexMax) exceeds 75% of JVM RAM
  ;; 2025-10-31 12:19:48     at datomic.error$arg.invokeStatic(error.clj:79)
  ;; 2025-10-31 12:19:48     at java.base/java.lang.Thread.run(Unknown Source)
  ;; 2025-10-31 12:20:18 Launching with Java options -server -Xms1g -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=50
  (memory-index-threshold
   (string "32m")
   "Threshold for Datomic indices to do something.")
  (memory-index-max
   (string "256m")
   "Maximum size for Datomic indices to be resident in-memory.")
  (object-cache-max
   (string "128m")
   "Maximum size for Datomic's in-memory object cache."))

(define (datomic-transactor-account-service config)
  "Return a list of <user-account>s and <user-group>s to create."
  (list
   (user-group (name "datomic") (system? #t))
   (user-account
     (name "datomic")
     (group "datomic")
     (system? #t)
     (comment "Datomic transactor user")
     (home-directory "/var/empty")
     (shell (file-append shadow "/sbin/nologin")))))

(define (datomic-dir config)
  (user-account-home-directory (first (datomic-accounts config))))

(define (datomic-transactor-profile-service config)
  "Return a list of <package>s to add to the system profile."
  (list
   (datomic-transactor-configuration-package config)))

(define (datomic-transactor-shepherd-service config)
  (let ((datomic (datomic-transactor-configuration-package config))
        (log-dir (datomic-transactor-configuration-log-dir config))
        (data-dir (datomic-transactor-configuration-data-dir config))
        (props-file (serialize-transactor-configuration config)))
    (list
     (shepherd-service
       (provision '(datomic-transactor))
       (requirement '(file-systems networking))
       (start #~(make-forkexec-constructor
                 (list (string-append #$datomic "/bin/transactor") #$props-file)
                 #:user "datomic"
                 #:group "datomic"
                 #:pid-file (string-append #$data-dir "/datomic-transactor.pid")
                 #:log-file (string-append #$log-dir "/transactor.log")
                 #:environment-variables
                 (list
                  (string-append
                   "PATH=" (string-join
                            (list
                             #$(file-append coreutils "/bin")
                             #$(file-append bash "/bin")
                             #$(file-append openjdk "/bin"))
                            ":" 'infix))
                  (string-append "DATOMIC_HOME=" #$datomic)
                  (string-append "DATOMIC_LOG_DIR=" #$log-dir))))
       (stop #~(make-kill-destructor))
       (documentation "Datomic Transactor")
       (actions
        (list
         (shepherd-configuration-action props-file)))))))

(define (datomic-transactor-activation-service config)
  "Return gexp to activate Datomic's transactor."
  (let ((log-dir (datomic-transactor-configuration-log-dir config))
        (data-dir (datomic-transactor-configuration-data-dir config)))
    #~(begin
        (use-modules (guix build utils))
        (define %user (getpw "datomic"))

        (mkdir-p #$log-dir)
        (chown #$log-dir (passwd:uid %user) (passwd:gid %user))

        (mkdir-p #$data-dir)
        (chown #$data-dir (passwd:uid %user) (passwd:gid %user)))))

(define datomic-transactor-service-type
  (service-type
    (name 'datomic-transactor)
    (description "Datomic Transactor")
    (extensions
     (list
      (service-extension profile-service-type
                         datomic-transactor-profile-service)
      (service-extension account-service-type
                         datomic-transactor-account-service)
      (service-extension activation-service-type
                         datomic-transactor-activation-service)
      (service-extension shepherd-root-service-type
                         datomic-transactor-shepherd-service)))
    (default-value (datomic-transactor-configuration))))

(define (generate-datomic-transactor-documentation)
  (generate-documentation
   `((datomic-transactor-configuration ,datomic-transactor-configuration-fields))
   'datomic-transactor-configuration))
